server:
  port: 8080

spring:
  application:
    name: APIGateWay

  cloud:
    gateway:
      routes:
        - id: greetApplication
          uri: lb://GREETAPI
          predicates:
            - Path=/gre/**
         

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
